
# The Conversao-Temperatura Web Application Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: conversao-temperatura-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: conversao-temperatura-app-deployment
  template:
    metadata:
      labels:
        app: conversao-temperatura-app-deployment
    spec: 
      containers:
      - name: conversao-temperatura-app
        image: thandi13/conversao-temperatura:v1
        ports:
          - containerPort: 8080
---
# The Conversao-Temperatura Web Application Service 
apiVersion: v1
kind: Service
metadata:
  name: conversao-temperatura-app-service
spec:
  selector:
    app: conversao-temperatura-app-deployment
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 30000 
  type: NodePort
